name: Build & Push WORKER (client6) to ECR + Deploy ECS

on:
  push:
    branches: [ main ]
    paths:
      - "worker/**"
      - ".github/workflows/client6-worker-build-push.yml"
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: 636851749897

  ECR_REPOSITORY: client6-backend-worker
  IMAGE_TAG: latest

  ECS_CLUSTER_NAME: client6-backend-cluster
  ECS_SERVICE_NAME: client6-backend-worker-service

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push WORKER image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy (force new deployment)
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER_NAME }}" \
            --service "${{ env.ECS_SERVICE_NAME }}" \
            --force-new-deployment

