name: Build & Push CRON (client7) to ECR

on:
  push:
    branches: [ main ]
    paths:
      - "cron/**"
      - ".github/workflows/client7-cron-build-push.yml"
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: 636851749897

  ECR_REPOSITORY: client7-backend-cron
  IMAGE_TAG: latest

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push CRON image
        uses: docker/build-push-action@v5
        with:
          context: ./cron
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

